const never_list = [
  "gone scuba diving.",
  "gone skydiving.",
  "gone bungee jumping.",
  "gone skinny dipping.",
  "gone camping in the wilderness.",
  "ridden a roller coaster.",
  "gone surfing.",
  "gone on a hot air balloon ride.",
  "climbed a mountain.",
  "attended a music festival.",
  "dyed my hair a wild color.",
  "tried bungee jumping.",
  "ridden a motorcycle.",
  "gone rock climbing.",
  "ridden a jet ski.",
  "gone parasailing.",
  "learned to surf.",
  "gone wakeboarding.",
  "ridden in a helicopter.",
  "been on a cruise.",
  "gone snowboarding.",
  "gone skiing.",
  "ridden a zip line.",
  "gone deep-sea fishing.",
  "gone whitewater rafting.",
  "gone hang gliding.",
  "ridden a camel.",
  "gone to a bar alone.",
  "gone to a club alone.",
  "gone to a camping site alone.",
  "gone to a library alone.",
  "gone to a bookstore alone.",
  "gone to a cafe alone.",
  "gone to a movie theater alone.",
  "gone to a museum alone.",
  "gone to a concert alone.",
];

const categories_list = [
  "Types of Fruit",
  "Colours (one word only)",
  "Dog Breeds",
  "Pizza Toppings",
  "Countries",
  "Car Brands",
  "Musical Instruments",
  "Zodiac (Star) Signs",
  "Flowers",
  "Capital Cities",
  "Ocean Animals",
  "Vegetables",
  "Musical Genres",
  "Currencies",
  "Disney Movies",
  "National Holidays",
  "Modes of Transportation",
  "Types of Tea",
  "Kitchen Appliances",
  "Types of Coffee",
  "Video Game Consoles",
  "Parts of a Computer",
  "Jungle Animals",
  "Languages",
  "Things that Fly",
  "Things that Swim",
  "Coding Languages",
  "Bank Names",
  "Fast Food Chains",
  "Planets",
  "Famous Landmarks",
  "Board Games",
  "Famous Artists",
  "Weather Phenomena",
  "Types of Cheese",
  "Famous Inventors",
  "Types of Pasta",
  "Desserts",
  "Famous Actors",
  "Cocktails",
  "Famous Authors",
  "Types of Wine",
  "Types of Fish",
  "Famous Singers",
  "Elements on the Periodic Table",
  "Types of Cameras",
  "Types of Smartwatches",
  "Types of Operating Systems",
  "Types of Web Browsers",
  "Social Media Platforms",
  "Video Streaming Services",
  "Music Streaming Services",
];

const rule_list = [
  {
    topic: "Thumb Master",
    description:
      "The player who draws a card becomes the Thumb Master., whenever the Thumb Master places their thumb on the table, all other players must quickly follow suit. The last player to do so must drink.",
  },
  {
    topic: "Left-Hand Rule",
    description:
      "Throughout the game, players can only pick up and drink with their left hand. If someone uses their right hand, they must drink.",
  },
  {
    topic: "Name Game",
    description:
      "Players must refer to each other by their first names only. If someone forgets and uses a nickname or last name, they must drink.",
  },
  {
    topic: "No Pointing",
    description: "Players cannot point at each other or anything in the room. If someone does, they must drink.",
  },
  {
    topic: "Rhyme Rule",
    description:
      "Throughout the game, players must speak in rhymes. If someone fails to rhyme or speaks normally, they must drink.",
  },
  {
    topic: "Eyes Closed",
    description:
      "Players must keep their eyes closed during their turn or when receiving instructions. If someone opens their eyes, they must drink.",
  },
  {
    topic: "Hands Off",
    description: "Players cannot touch their face or hair. If someone does, they must drink.",
  },
  {
    topic: "Silent Laugh",
    description:
      "Players must silently laugh instead of laughing out loud. If someone audibly laughs, they must drink.",
  },
  {
    topic: "Foreign Language Only",
    description:
      "Players must communicate in a language that is not their native language. If someone speaks in their native language, they must drink.",
  },
  {
    topic: "No this word",
    description: "Players cannot use certain designated words. If someone does, they must drink.",
  },
  {
    topic: "No pronoun",
    description: "Players cannot use pronouns. If someone does, they must drink.",
  },
];
