const never_list = [
  "danced in rain",
  "lost my keys",
  "slept in class",
  "sung in public",
  "fallen off a bike",
  "tripped in public",
  "eaten dessert first",
  "laughed uncontrollably",
  "worn mismatched socks",
  "snorted while laughing",
  "talked to my pet",
  "had food poisoning",
  "missed a flight",
  "been late to work",
  "dropped my phone",
  "lost a shoe",
  "walked into glass",
  "taken a selfie",
  "worn pajamas outside",
  "danced like no one’s watching",
  "forgotten a friend’s name",
  "used the wrong name",
  "tried learning guitar",
  "dyed my hair",
  "bought useless stuff",
  "laughed at a meme",
  "sung karaoke",
  "mistaken a stranger",
  "overslept an alarm",
  "binged a whole series",
  "worn a costume",
  "baked a cake",
  "forgotten my wallet",
  "broken a remote",
  "sent the wrong text",
  "spilled a drink",
  "missed a high five",
  "walked into a pole",
  "gotten lost",
  "spilled coffee",
  "faked a laugh",
  "eaten a bug",
  "jumped in fear",
  "missed a bus",
  "slept through class",
  "eaten too much",
  "snuck snacks in",
  "fed pigeons",
  "cried at a movie",
  "worn socks to bed",
  "forgotten my password",
  "done a silly dance",
  "overwatered a plant",
  "sung in the shower",
  "worn sunglasses indoors",
  "put salt in coffee",
  "taken a bad photo",
  "confused twins",
  "burped in public",
  "dropped my ice cream",
  "left a Zoom mic on",
  "googled my name",
  "gotten sunburned",
  "been photobombed",
  "bought too much candy",
  "hugged a tree",
  "mistaken a mannequin",
  "worn a backwards shirt",
  "failed a high five",
  "worn two different shoes",
  "tried to juggle",
  "gotten hiccups",
  "spilled soup",
  "waved at a stranger",
  "lost my hat",
  "worn shoes wrong feet",
  "pretended to know lyrics",
  "made a silly face",
  "eaten a full pizza",
  "fallen asleep talking",
  "tried parkour",
  "forgotten my towel",
  "dropped a fork",
  "sneezed while eating",
  "mixed up days",
  "eaten cold pizza",
  "won a raffle",
  "worn flip flops wrong",
  "been stuck in mud",
  "caught a snowflake",
  "made a snow angel",
  "worn mismatched gloves",
  "baked cookies",
  "taken a nap outside",
  "used a silly nickname",
  "forgotten my sunglasses",
  "tried to moonwalk",
  "lost my sunglasses",
  "sneezed in a mask",
  "eaten cereal for dinner",
];

const categories_list = [
  "Types of Fruit",
  "Colours (one word only)",
  "Dog Breeds",
  "Pizza Toppings",
  "Countries",
  "Car Brands",
  "Musical Instruments",
  "Zodiac (Star) Signs",
  "Flowers",
  "Capital Cities",
  "Ocean Animals",
  "Vegetables",
  "Musical Genres",
  "Currencies",
  "Disney Movies",
  "National Holidays",
  "Modes of Transportation",
  "Types of Tea",
  "Kitchen Appliances",
  "Types of Coffee",
  "Video Game Consoles",
  "Parts of a Computer",
  "Jungle Animals",
  "Languages",
  "Things that Fly",
  "Things that Swim",
  "Coding Languages",
  "Bank Names",
  "Fast Food Chains",
  "Planets",
  "Famous Landmarks",
  "Board Games",
  "Famous Artists",
  "Weather Phenomena",
  "Types of Cheese",
  "Famous Inventors",
  "Types of Pasta",
  "Desserts",
  "Famous Actors",
  "Cocktails",
  "Famous Authors",
  "Types of Wine",
  "Types of Fish",
  "Famous Singers",
  "Elements on the Periodic Table",
  "Types of Cameras",
  "Types of Smartwatches",
  "Types of Operating Systems",
  "Types of Web Browsers",
  "Social Media Platforms",
  "Video Streaming Services",
  "Music Streaming Services",
];

const rule_list = [
  {
    topic: "Thumb Master",
    description:
      "The player who draws a card becomes the Thumb Master., whenever the Thumb Master places their thumb on the table, all other players must quickly follow suit. The last player to do so must drink.",
  },
  {
    topic: "Left-Hand Rule",
    description:
      "Throughout the game, players can only pick up and drink with their left hand. If someone uses their right hand, they must drink.",
  },
  {
    topic: "Name Game",
    description:
      "Players must refer to each other by their first names only. If someone forgets and uses a nickname or last name, they must drink.",
  },
  {
    topic: "No Pointing",
    description: "Players cannot point at each other or anything in the room. If someone does, they must drink.",
  },
  {
    topic: "Rhyme Rule",
    description:
      "Throughout the game, players must speak in rhymes. If someone fails to rhyme or speaks normally, they must drink.",
  },
  {
    topic: "Eyes Closed",
    description:
      "Players must keep their eyes closed during their turn or when receiving instructions. If someone opens their eyes, they must drink.",
  },
  {
    topic: "Hands Off",
    description: "Players cannot touch their face or hair. If someone does, they must drink.",
  },
  {
    topic: "Silent Laugh",
    description:
      "Players must silently laugh instead of laughing out loud. If someone audibly laughs, they must drink.",
  },
  {
    topic: "Foreign Language Only",
    description:
      "Players must communicate in a language that is not their native language. If someone speaks in their native language, they must drink.",
  },
  {
    topic: "No this word",
    description: "Players cannot use certain designated words. If someone does, they must drink.",
  },
  {
    topic: "No pronoun",
    description: "Players cannot use pronouns. If someone does, they must drink.",
  },
];
