const never_list = [
  "eaten sushi.",
  "gone scuba diving.",
  "ridden a horse.",
  "gone skydiving.",
  "traveled to another continent.",
  "learned to play a musical instrument.",
  "gone bungee jumping.",
  "gone skinny dipping.",
  "sung karaoke in front of a crowd.",
  "been on a blind date.",
  "gone camping in the wilderness.",
  "ridden a roller coaster.",
  "gone surfing.",
  "gone on a hot air balloon ride.",
  "climbed a mountain.",
  "attended a music festival.",
  "dyed my hair a wild color.",
  "tried bungee jumping.",
  "ridden a motorcycle.",
  "gone rock climbing.",
  "ridden a jet ski.",
  "gone parasailing.",
  "learned to surf.",
  "gone wakeboarding.",
  "ridden in a helicopter.",
  "been on a cruise.",
  "gone snowboarding.",
  "gone skiing.",
  "ridden a zip line.",
  "gone deep-sea fishing.",
  "gone on a safari.",
  "ridden an elephant.",
  "gone whitewater rafting.",
  "gone hang gliding.",
  "ridden a camel.",
  "gone on a road trip with friends.",
  "gone on a spontaneous trip.",
  "gone on a solo trip.",
  "gone to a music concert alone.",
  "gone to a movie alone.",
  "gone to a restaurant alone.",
  "gone to a bar alone.",
  "gone to a club alone.",
  "gone to a party alone.",
  "gone to a wedding alone.",
  "gone to a funeral alone.",
  "gone to a theme park alone.",
  "gone to a carnival alone.",
  "gone to a fair alone.",
  "gone to a beach alone.",
  "gone to a park alone.",
  "gone to a hiking trail alone.",
  "gone to a camping site alone.",
  "gone to a library alone.",
  "gone to a bookstore alone.",
  "gone to a cafe alone.",
  "gone to a movie theater alone.",
  "gone to a museum alone.",
  "gone to a concert alone.",
  "gone to a sports event alone.",
  "gone to a zoo alone.",
  "gone to an aquarium alone.",
  "gone to a botanical garden alone.",
  "gone to a picnic alone.",
  "gone to a potluck alone.",
  "gone to a barbecue alone.",
  "gone to a club alone.",
  "gone to a bar alone.",
  "gone to a casino alone.",
  "gone to a strip club alone.",
  "gone to a spa alone.",
  "gone to a massage parlor alone.",
];

const categories_list = [
  "Types of Fruit",
  "Colours (one word only)",
  "Dog Breeds",
  "Pizza Toppings",
  "Countries",
  "Car Brands",
  "Musical Instruments",
  "Zodiac (Star) Signs",
  "Flowers",
  "Capital Cities",
  "Ocean Animals",
  "Vegetables",
  "Musical Genres",
  "Currencies",
  "Disney Movies",
  "National Holidays",
  "Modes of Transportation",
  "Types of Tea",
  "Kitchen Appliances",
  "Types of Coffee",
  "Video Game Consoles",
  "Parts of a Computer",
  "Jungle Animals",
  "Languages",
  "Things that Fly",
  "Things that Swim",
  "Coding Languages",
  "Bank Names",
  "Fast Food Chains",
  "Planets",
  "Famous Landmarks",
  "Board Games",
  "Famous Artists",
  "Weather Phenomena",
  "Types of Cheese",
  "Famous Inventors",
  "Types of Pasta",
  "Desserts",
  "Famous Actors",
  "Cocktails",
  "Famous Authors",
  "Types of Wine",
  "Types of Fish",
  "Famous Singers",
  "Elements on the Periodic Table",
  "Types of Cameras",
  "Types of Smartwatches",
  "Types of Operating Systems",
  "Types of Web Browsers",
  "Social Media Platforms",
  "Video Streaming Services",
  "Music Streaming Services",
];

const rule_list = [
  {
    topic: "Thumb Master",
    description:
      "The player who draws a card becomes the Thumb Master. Throughout the game, whenever the Thumb Master places their thumb on the table, all other players must quickly follow suit. The last player to do so must drink.",
  },
  {
    topic: "Waterfall",
    description:
      "When a player draws a card, everyone must start drinking. The player who drew the card can stop drinking whenever they want, followed by the player to their left, and so on around the circle. No one can stop drinking until the person to their right stops.",
  },
  {
    topic: "No Swearing",
    description:
      "Players cannot swear or use certain designated words throughout the game. If someone does, they must drink.",
  },
  {
    topic: "Silent Rule",
    description:
      "The player who draws a card cannot speak for the rest of the game round. If they do, they must drink.",
  },
  {
    topic: "Left-Hand Rule",
    description:
      "Throughout the game, players can only pick up and drink with their left hand. If someone uses their right hand, they must drink.",
  },
  {
    topic: "Name Game",
    description:
      "Players must refer to each other by their first names only. If someone forgets and uses a nickname or last name, they must drink.",
  },
  {
    topic: "Three Strikes",
    description:
      "Each player is allowed three 'strikes' throughout the game. If they break a rule or fail to follow a directive, they receive a strike. Upon receiving three strikes, they must finish their drink.",
  },
  {
    topic: "No Pointing",
    description: "Players cannot point at each other or anything in the room. If someone does, they must drink.",
  },
  {
    topic: "Rhyme Rule",
    description:
      "Throughout the game, players must speak in rhymes. If someone fails to rhyme or speaks normally, they must drink.",
  },
  {
    topic: "Eyes Closed",
    description:
      "Players must keep their eyes closed during their turn or when receiving instructions. If someone opens their eyes, they must drink.",
  },
];
